Repository GTeamx/VPNSetup, pull requests merged in 2024-08, with the labels that each got.

#9 Update auto_setup.sh
  auto_setup.sh
Labels: enhancement

#10 Update README.md
  README.md
Labels: quick-fix

#12 Update README.md
  README.md
Labels: documentation, quick-fix

#14 WireGuard remake/uplift
  README.md
  auto_setup.sh
Labels: major-update
